security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
server:
  port: ${APP_PORT:9009}
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: changeit
    key-password: changeit